spring.application.name=miniproject_pet_260124

# View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle DataSource
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
#spring.datasource.username=mini
#spring.datasource.password=mini

# PostgreSQL DataSource (Railway)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA Dialect (PostgreSQL용 번역기)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# 파일 업로드 제한 (개별 파일 최대 100MB)
spring.servlet.multipart.max-file-size=100MB

# 전체 요청 최대 업로드 용량 (예: 512MB)
spring.servlet.multipart.max-request-size=512MB
