-- 시퀀스 삭제
-- 시퀀스 삭제 별 의미 없음 (PostgreSQL이라서 그럼)
DROP SEQUENCE IF EXISTS seq_mem_idx;
DROP SEQUENCE IF EXISTS seq_pet_idx;
DROP SEQUENCE IF EXISTS seq_item_idx;
DROP SEQUENCE IF EXISTS seq_cart_idx;
DROP SEQUENCE IF EXISTS seq_cart_item_idx;
DROP SEQUENCE IF EXISTS seq_orders_idx;
DROP SEQUENCE IF EXISTS seq_orders_item_idx;
DROP SEQUENCE IF EXISTS seq_board_idx;
DROP SEQUENCE IF EXISTS seq_board_file_idx;
DROP SEQUENCE IF EXISTS seq_reply_idx;

-- 자식 테이블부터 삭제
DROP TABLE IF EXISTS reply CASCADE;
DROP TABLE IF EXISTS board_file CASCADE;
DROP TABLE IF EXISTS board CASCADE;

DROP TABLE IF EXISTS orders_item CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS cart_item CASCADE;
DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS item CASCADE;

DROP TABLE IF EXISTS pet CASCADE;

DROP TABLE IF EXISTS member_addr CASCADE;
DROP TABLE IF EXISTS member_profile CASCADE;
DROP TABLE IF EXISTS member CASCADE;

-- 코드 테이블들
DROP TABLE IF EXISTS board_type CASCADE;
DROP TABLE IF EXISTS orders_status CASCADE;
DROP TABLE IF EXISTS item_type CASCADE;
DROP TABLE IF EXISTS grade CASCADE;
DROP TABLE IF EXISTS role CASCADE;