/*
-- 시퀀스 삭제
DROP SEQUENCE seq_mem_idx;
DROP SEQUENCE seq_pet_idx;
DROP SEQUENCE seq_item_idx;
DROP SEQUENCE seq_cart_idx;
DROP SEQUENCE seq_cart_item_idx;
DROP SEQUENCE seq_orders_idx;
DROP SEQUENCE seq_orders_item_idx;
DROP SEQUENCE seq_board_idx;
DROP SEQUENCE seq_board_file_idx;
DROP SEQUENCE seq_reply_idx;


-- FK 많이 물고 있는 애들부터 (자식 테이블들)
DROP TABLE reply CASCADE CONSTRAINTS;
DROP TABLE board_file CASCADE CONSTRAINTS;
DROP TABLE board CASCADE CONSTRAINTS;

DROP TABLE orders_item CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;

DROP TABLE cart_item CASCADE CONSTRAINTS;
DROP TABLE cart CASCADE CONSTRAINTS;
DROP TABLE item CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE member_addr CASCADE CONSTRAINTS;
DROP TABLE member_profile CASCADE CONSTRAINTS;
DROP TABLE member CASCADE CONSTRAINTS;

-- 코드 테이블들
DROP TABLE board_type CASCADE CONSTRAINTS;
DROP TABLE orders_status CASCADE CONSTRAINTS;
DROP TABLE item_type CASCADE CONSTRAINTS;
DROP TABLE grade CASCADE CONSTRAINTS;
DROP TABLE role CASCADE CONSTRAINTS;

*/